### ISSUE TITLE
Book outline

### ISSUE THREAD

**Issue by bIgBV** [rustasync/book#1]
This issue is to discuss the outline of the Rust Async book

**Comment by tirr-c** [comment]
It would be good to have an FAQ section with code snippet examples. I often get questions like "how can I run `Future` first, and `await` later?" `Future` with `Pin` also comes to my mind, but I have no idea of what the question would be.

**Comment by LucioFranco** [comment]
@tirr-c I like that a futures based cook book thing!

**Comment by bIgBV** [comment]
It'd be pretty useful to collect all common questions in one place so that we could include them in such a cookbook.

**Comment by jbcden** [comment]
This is not really a concrete idea but it would be nice to walk people through how things work under the hood -- or maybe this is a separate "book"/tutorial (not sure if this is more of a "here's how to use this" or "here's how this works low-level details" kind of book) . @jonhoo did something like this in a stream back in November and I found the breakdown very helpful!

**Edit:** here's the link to the referenced video: https://www.youtube.com/watch?v=9_3krAQtD2k

**Comment by LucioFranco** [comment]
I think that is what the actual `async-book` will do.

**Comment by LucioFranco** [comment]
We are going to defer to https://github.com/rust-lang/async-book
